### ISSUE TITLE
No motion update

### ISSUE THREAD

**Issue by jumpjack** [nickrehm/LanderSim#3]
Nothing changes in speeds upon changing parameters: if gravity or weight is increased, vertical speed should increase too.

**Comment by nickrehm** [comment]
The normalized thrust command is intentionally scaled to 0-2g's of the current set gravity and mass. So changing mass or gravity but leaving throttle at 50% gives 1g worth of thrust in the local gravity, and the body therefore remains stationary. This is intentional to avoid needing an additional tunable parameter for "max engine thrust" that would need to be manually changed for different masses/gravities--the current implementation uncouples this so we can focus on landing physics and not engine sizing :)
